//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Escasan_Api.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Productos
    {
        public int IdProducto { get; set; }
        public string Codigo { get; set; }
        public string CodIPSA { get; set; }
        public string Producto { get; set; }
        public Nullable<int> IdUnidad { get; set; }
        public int IdGrupo { get; set; }
        public int IdSubGrupo { get; set; }
        public Nullable<int> IdGrupoPresupuestario { get; set; }
        public Nullable<int> IdImpuesto { get; set; }
        public Nullable<int> IdProveedor { get; set; }
        public Nullable<decimal> CostoPromedio { get; set; }
        public Nullable<bool> Activo { get; set; }
        public Nullable<bool> Estrategico { get; set; }
        public string CodigoBarra { get; set; }
        public string Clasificacion { get; set; }
        public Nullable<decimal> Existencia { get; set; }
        public Nullable<bool> ControladoPorLote { get; set; }
        public Nullable<bool> FacturaNegativo { get; set; }
        public string SAC { get; set; }
        public string CodigoProoveedor { get; set; }
        public decimal CostoInicial { get; set; }
        public string GRUPO { get; set; }
        public string SUBGRUPO { get; set; }
        public string GrupoPresu { get; set; }
        public string UNIDAD { get; set; }
    }
}
